dist: trusty
group: travis_latest
language: generic

language: generic

services:
  - docker

before_script:
  - IFS='/' read -ra TMP <<< "$TRAVIS_REPO_SLUG"
  - if [ -z ${USERNAME+x} ]; then export "USERNAME=${TMP[0]}"; fi
  - if [ -z ${IMAGE+x} ];    then export "IMAGE=${TMP[1]}"; fi

script:
  - docker build -t "${USERNAME}/${IMAGE}:latest" .

deploy:
  skip_cleanup: true
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "${USERNAME}/${IMAGE}:latest"
    
