sudo: required

language: generic

services:
  - docker

before_script:
  - IFS='/' read -ra TMP <<< "$TRAVIS_REPO_SLUG"
  - echo "${TMP[0]}"
  - if [ -z ${USERNAME+x} ]; then export "USERNAME=${TMP[0]}";
  - if [ -z ${IMAGE+x} ];    then export "IMAGE=${TMP[1]}";

script:
  - docker build -t "${USERNAME}/${IMAGE}":latest .

deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "${USERNAME}/${IMAGE}:latest"
    
