---
language: generic

cache:
  bundler: true
  directories:
    - $HOME/docker

services:
  - docker

before_script:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - env
  - ./build.sh --print-vars
  - ./build.sh --build
  - bash -x ./test/run_tests.sh

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

deploy:
  skip_cleanup: true
  provider: script
  script:
    - env
    - ./build.sh --deploy
  on:
    all_branches: true

